{% set name = "dvc" %}
{% set version = "0.86.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 748dd0cf890c2f1f731d4dd7489cb4bfb3267a77d03a904976dfadde545fa0cb
  patches:
    - build.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]
  entry_points:
    - dvc = dvc.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil <2.8.1,>=2.1
    - ply >=3.9
    - colorama >=0.3.9
    - configobj >=5.0.6
    - gitpython >=3
    - setuptools >=34.0.0
    - nanotime >=0.5.2
    - pyasn1 >=0.4.1
    - voluptuous >=0.11.7
    - jsonpath-ng >=1.4.3
    - requests >=2.22.0
    - grandalf ==0.6
    - distro >=1.3.0
    - appdirs >=1.4.3
    - treelib >=1.5.5
    - inflect >=2.1.0,<4
    - humanize >=0.5.1
    - pyyaml >=5.1.2,<5.2
    - ruamel.yaml >=0.16.1
    - funcy >=1.14
    - pathspec >=0.6.0
    - shortuuid >=0.5.0
    - tqdm >=4.40.0,<5
    - packaging >=19.0
    - zc.lockfile >=1.2.1
    - flufl.lock >=3.2
    - win_unicode_console >=0.5  # [win]
    - pywin32 >=225  # [win]
    - networkx >=2.1,<2.4
    - pydot >=1.2.4
    - flatten_json >=0.1.6
    - texttable >=0.5.2
    - google-cloud-storage ==1.19.0
    - pydrive2 ==1.4.5
    - boto3 >=1.9.201
    - azure-storage-blob ==2.1.0
    - oss2 ==2.6.1
    - paramiko >=2.5.0
    - pyarrow ==0.15.1

test:
  requires:
    - git
  imports:
    - dvc
  commands:
    - dvc version -v
    - dvc get https://github.com/iterative/dvc scripts/innosetup/dvc.ico -v

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'DVC tracks ML models and data sets'

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - MaxRis
