{% set name = "dvc" %}
{% set version = "0.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14233a4063dfcfaf3ba38cd2cb87ce0439c7eda5db1761ee94a0ae35e2db6a86

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - dvc = dvc.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ply >=3.9
    - configparser >=3.5.0
    - zc.lockfile >=1.2.1
    - future >=0.16.0
    - colorama >=0.3.9
    - configobj >=5.0.6
    - gitpython >=2.1.8
    - setuptools >=34.0.0
    - nanotime >=0.5.2
    - pyasn1 >=0.4.1
    - schema >=0.6.7
    - jsonpath-ng >=1.4.3
    - requests >=2.22.0
    - grandalf ==0.6
    - asciimatics >=1.10.0
    - distro >=1.3.0
    - appdirs >=1.4.3
    - treelib >=1.5.5
    - inflect >=2.1.0
    - humanize >=0.5.1
    - ruamel.yaml >=0.15.91,<0.16
    - funcy >=1.12
    - pathspec >=0.5.9
    - shortuuid >=0.5.0
    - win-unicode-console >=0.5  # [win]
    - networkx >=2.1
    - futures  # [py==27]
    - pathlib2  # [py==27]
    - google-cloud-storage ==1.13.0
    - boto3 ==1.9.115
    - azure-storage-blob ==2.1.0
    - oss2 ==2.6.1
    - paramiko >=2.5.0
    - pyarrow ==0.14.0  # [py>27 or unix]

test:
  imports:
    - dvc

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'DVC tracks ML models and data sets'

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - MaxRis
