{% set name = "dvc" %}
{% set version = "2.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e528f3dfc22b02d25c79ff2791f02c3fd5706b8320e071ba18789a6f60e2fe6
  patches:
    - build.patch

# The "true" build is specified in the dvc output below.
# Of the build properties here and below:
# number is propagated into the outputs below
build:
  number: 1
  skip: true  # [py<=36 and win]

outputs:
  - name: dvc
    build:
      entry_points:
        - dvc = dvc.main:main
      script:
        - python -m pip install . --no-deps -vv

    # Base package supports dvc, but only supports built-in remotes
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - 'dvc version | grep "Supports: http, https"'

    requirements:
      host:
        - python
        - pip
      run:
        - python
        - ply >=3.9
        - colorama >=0.3.9
        - configobj >=5.0.6
        - gitpython >=2.1.8
        - dulwich >=0.20.21
        - pygit2 >=1.5.0
        - gitdb2 >=2.0.6
        - setuptools >=34.0.0
        - nanotime >=0.5.2
        - pyasn1 >=0.4.1
        - voluptuous >=0.11.7
        - jsonpath-ng >=1.4.3
        - requests >=2.22.0
        - grandalf ==0.6
        - distro >=1.3.0
        - appdirs >=1.4.3
        - ruamel.yaml >=0.16.1
        - toml >=0.10.1
        - funcy >=1.14
        - pathspec >=0.6.0
        - shortuuid >=0.5.0
        - tqdm >=4.45.0,<5
        - packaging >=19.0
        - zc.lockfile >=1.2.1
        - flufl.lock >=3.2,<4
        - win_unicode_console >=0.5  # [win]
        - pywin32 >=225  # [win]
        - networkx >=2.1
        - psutil >=5.8.0
        - pydot >=1.2.4
        - dataclasses  # [py<37]
        - flatten-dict >=0.3.0,<1
        - tabulate >=0.8.7
        - pygtrie ==2.3.2
        - dpath >=1.4.2
        - shtab >=1.3.2,<2
        - rich >=10.0.0
        - dictdiffer>=0.8.1
        - python-benedict >=0.21.1
        - pyparsing ==2.4.7
        - typing_extensions >=3.7.4
        - fsspec >=0.8.5
        - diskcache >=5.2.1

  - name: dvc-gs
    test:
      requires:
        - git
        - pip
        - importlib-metadata  # Undeclared upstream dependency
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep gs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - gcsfs >=0.7.2

  - name: dvc-gdrive
    test:
      requires:
        - git
        - pip
        - importlib-metadata  # Undeclared upstream dependency
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep gdrive
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - pydrive2 >=1.8.1

  - name: dvc-s3
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep s3
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - boto3 >=1.9.201

  - name: dvc-azure
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep azure
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - adlfs >=0.7.0
        - azure-identity >=1.4.0
        - knack

  - name: dvc-oss
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep oss
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - oss2 >=2.11.0

  - name: dvc-ssh
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep ssh
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - paramiko >=2.7.0
        # for paramiko, see https://github.com/iterative/dvc/issues/4589
        - invoke >=1.3

  - name: dvc-hdfs
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep hdfs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - pyarrow >=0.17.1

  - name: dvc-webhdfs
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep webhdfs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - python-hdfs >=2.5.7

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - skshetry
