{% set name = "dvc" %}
{% set version = "3.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c04f40b4471b695cbe5452a6cbffac47d078863f7e462da2208238e6fb813ab5
  patches:
    - build.patch

build:
  noarch: python
  number: 0
  entry_points:
    - dvc = dvc.cli:main
  script:
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=7
  run:
    - gto >=1.4.0,<2
    - colorama >=0.3.9
    - configobj >=5.0.6
    - distro >=1.3
    - dpath <3,>=2.1.0
    - dvc-data >=2.18.1,<2.19.0
    - dvc-http >=2.29.0
    - dvc-render >=0.3.1,<1
    - dvc-studio-client >=0.13.0,<1
    - dvc-task >=0.3.0,<1
    - flatten-dict <1,>=0.4.1
    - flufl.lock >=5,<8
    - funcy >=1.14
    - grandalf <1,>=0.7
    - hydra-core >=1.1
    - iterative-telemetry >=0.0.7
    - networkx >=2.5
    - packaging >=19
    - pathspec >=0.10.3
    - platformdirs <4,>=3.1.1
    - psutil >=5.8
    - pydot >=1.2.4
    - pygtrie >=2.3.2
    - pyparsing >=2.4.7
    - python >=3.8
    - requests >=2.22
    - rich >=12
    - ruamel.yaml >=0.17.11
    - scmrepo >=1.2.1,<2
    - shortuuid >=0.5
    - shtab <2,>=1.3.4
    - tabulate >=0.8.7
    - tomlkit >=0.11.1
    - tqdm <5,>=4.63.1
    - voluptuous >=0.11.7
    - zc.lockfile >=1.2.1

# Base package supports dvc, but only supports built-in remotes
test:
  requires:
    - git
    - pip
  imports:
    - dvc
    - dvc.repo
  commands:
    - pip check
    - dvc version
    - dvc version | grep {{ version }}
    - dvc version | grep https

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - daavoo
    - shcheklein
    - efiop
    - skshetry
    - pmrowla
    - weiji14
