{% set name = "dvc" %}
{% set version = "2.30.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8b129fd16aa58da280532c55859711ea7e0a727512681be6771dbb05e7ee5dc
  patches:
    - build.patch

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - dvc = dvc.main:main
  script:
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ply >=3.9
    - colorama >=0.3.9
    - configobj >=5.0.6
    - setuptools >=48
    - nanotime >=0.5.2
    - pyasn1 >=0.4.1
    - voluptuous >=0.11.7
    - requests >=2.22.0
    - grandalf ==0.6
    - distro >=1.3.0
    - appdirs >=1.4.3
    - ruamel.yaml >=0.17.11
    - toml >=0.10.1
    - tomlkit >=0.11.1
    - funcy >=1.14
    - pathspec >=0.9.0,<0.10.0
    - shortuuid >=0.5.0
    - tqdm >=4.63.1,<5
    - packaging >=19.0
    - zc.lockfile >=1.2.1
    - flufl.lock >=5
    - networkx >=2.5,<2.8.3
    - psutil >=5.8.0
    - pydot >=1.2.4
    - importlib_resources >=5.2.2  # [py<39]
    - flatten-dict >=0.4.1,<1
    - tabulate >=0.8.7
    - pygtrie >=2.3.2
    - dpath >=2.0.2,<3
    - shtab >=1.3.4,<2
    - rich >=10.13.0
    - dictdiffer >=0.8.1
    - pyparsing ==2.4.7
    - typing_extensions >=3.7.4
    - fsspec >=2021.10.1
    - aiohttp-retry >=2.4.5
    - diskcache >=5.2.1
    - scmrepo ==0.1.1
    - dvc-render ==0.0.12
    - dvclive >=0.10.0
    - dvc-data ==0.17.1
    - dvc-http ==2.27.2
    - dvc-task ==0.1.3
    - hydra-core >=1.1.0
    - iterative-telemetry ==0.0.5

# Base package supports dvc, but only supports built-in remotes
test:
  requires:
    - git
    - pip
  imports:
    - dvc
    - dvc.repo
  commands:
    - pip check
    - dvc version
    - dvc version | grep {{ version }}
    - dvc version | grep https

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - daavoo
    - shcheklein
    - efiop
    - skshetry
    - pmrowla
