{% set name = "dvc" %}
{% set version = "3.59.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d991221eec54a146050f90b948e5a9c0541c81565356bf034e3faf54a6bfb847
  patches:
    - build.patch

build:
  noarch: python
  number: 0
  entry_points:
    - dvc = dvc.cli:main
  script:
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=7
  run:
    - python >={{ python_min }}
    - attrs >=22.2.0
    - celery
    - colorama >=0.3.9
    - configobj >=5.0.9
    - distro >=1.3
    - dpath <3,>=2.1.0
    - dulwich
    - dvc-data >=3.16.2,<3.17
    - dvc-http >=2.29.0
    - dvc-objects
    - dvc-render >=1.0.1,<2
    - dvc-studio-client >=0.21,<1
    - dvc-task >=0.3.0,<1
    - flatten-dict <1,>=0.4.1
    - flufl.lock >=8.1.0,<9
    - fsspec >=2024.2.0
    - funcy >=1.14
    - grandalf <1,>=0.7
    - gto >=1.6.0,<2
    - hydra-core >=1.1
    - iterative-telemetry >=0.0.7
    - kombu
    - networkx >=2.5
    - omegaconf
    - packaging >=19
    - pathspec >=0.10.3
    - platformdirs <5,>=3.1.1
    - psutil >=5.8
    - pydot >=1.2.4
    - pygtrie >=2.3.2
    - pyparsing >=2.4.7
    - requests >=2.22
    - rich >=12
    - ruamel.yaml >=0.17.11
    - scmrepo >=3.3.8,<4
    - shortuuid >=0.5
    - shtab <2,>=1.3.4
    - tabulate >=0.8.7
    - tomlkit >=0.11.1
    - tqdm <5,>=4.63.1
    - voluptuous >=0.11.7
    - zc.lockfile >=1.2.1

# Base package supports dvc, but only supports built-in remotes
test:
  requires:
    - git
    - pip
    - python {{ python_min }}
  imports:
    - dvc
    - dvc.repo
  commands:
    - pip check
    - dvc version
    - dvc version | grep {{ version }}
    - dvc version | grep https

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - daavoo
    - shcheklein
    - efiop
    - skshetry
    - pmrowla
    - weiji14
