{% set name = "dvc" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 777020ed96d411cd0257ea4fdb842307a02a187b6ff8eacb7d97397507b5a007
  patches:
    - build.patch

# The "true" build is specified in the dvc output below.
# Of the build properties here and below:
# number is propagated into the outputs below
build:
  number: 0
  skip: true  # [py<=37 and win]


outputs:
  - name: dvc
    build:
      entry_points:
        - dvc = dvc.main:main
      script:
        - python -m pip install . --no-deps -vv

    # Base package supports dvc, but only supports built-in remotes
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - 'dvc version | grep "Supports: http, https"'

    requirements:
      host:
        - python
        - pip
      run:
        - python
        - ply >=3.9
        - colorama >=0.3.9
        - configobj >=5.0.6
        - gitpython >3
        - dulwich >=0.20.23
        - pygit2 >=1.5.0
        - setuptools >=48
        - nanotime >=0.5.2
        - pyasn1 >=0.4.1
        - voluptuous >=0.11.7
        - requests >=2.22.0
        - grandalf ==0.6
        - distro >=1.3.0
        - appdirs >=1.4.3
        - ruamel.yaml >=0.17.11
        - toml >=0.10.1
        - funcy >=1.14
        - pathspec >=0.9.0,<0.10.0
        - shortuuid >=0.5.0
        - tqdm >=4.45.0,<5
        - packaging >=19.0
        - zc.lockfile >=1.2.1
        - flufl.lock >=5
        - networkx >=2.5
        - psutil >=5.8.0
        - pydot >=1.2.4
        - importlib-metadata >=1.4  # [py<38]
        - importlib_resources >=5.2.2  # [py<39]
        - flatten-dict >=0.4.1,<1
        - tabulate >=0.8.7
        - pygtrie >=2.3.2
        - dpath >=2.0.1,<3
        - shtab >=1.3.4,<2
        - rich >=10.9.0
        - dictdiffer >=0.8.1
        - python-benedict >=0.24.2
        - pyparsing ==2.4.7
        - typing_extensions >=3.7.4
        - fsspec >=2021.10.1
        - aiohttp-retry >=2.4.5
        - diskcache >=5.2.1
        - scmrepo ==0.0.3

  - name: dvc-gs
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep gs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - gcsfs ==2021.10.1

  - name: dvc-gdrive
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep gdrive
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - pydrive2 >=1.10.0

  - name: dvc-s3
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep s3
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - s3fs ==2021.10.1
        - aiobotocore >1.0.1
        - boto3 >=1.9.201

  - name: dvc-azure
    test:
      requires:
        - git
        - pip
        - portalocker >=1.6,<2.0  # Temporary; see discussion around <https://github.com/conda-forge/dvc-feedstock/pull/234#issuecomment-907311619>
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep azure
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - adlfs >=2021.9.1
        - azure-identity >=1.4.0
        - knack

  - name: dvc-oss
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep oss
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - ossfs >=2021.8.0

  - name: dvc-ssh
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep ssh
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - sshfs >=2021.8.1

  - name: dvc-hdfs
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep hdfs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - pyarrow >=0.17.1

  - name: dvc-webdav
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep webdav
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}
        - webdav4 >=0.9.3

# NOTE: webhdfs support is baked into the main package.
# Keeping this one for backward compatibility.
  - name: dvc-webhdfs
    test:
      requires:
        - git
        - pip
      imports:
        - dvc
      commands:
        - pip check
        - dvc version
        - dvc version | grep webhdfs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("dvc", exact=True) }}

about:
  home: https://dvc.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DVC tracks ML models and data sets

  description: |
    Data Version Control or DVC is an open-source tool for data science
    and machine learning projects.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - skshetry
    - maresb
